### PR TITLE
align makefile with other projects

### PR DESCRIPTION
**Pull request by tobru**
This PR aligns the Makefile with other projects we're using. It mainly makes sure that `make preview` is available to have the local preview up and running, instead of `make docs-serve`, like in any other Antora documentation project we're having.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.

### CODE REVIEW

**Comment by ccremer** [comment]
I'm not sure which projects you are referring to, but for the components it's more of a disalignment now :D
(the components use make docs-serve, also in modulesync template f.e.)

**Comment by tobru** [comment]
Oh noes... Then, let's forget about it

**Comment by ccremer** [comment]
not so hasty :)
I'm not opposed to the change. in fact it seems to improve certain areas and we could consider it making into the modulesync and component template so that at least new and m-managed components benefit from new spellers etc.

**Comment by tobru** [comment]
I didn't mean to invest too much time, and I'm unsure if it's feasible for other non-docs-only related projects. As I'm currently mostly working with docs-only repos (aka Makefiles), the most common command I'm using is `make preview`, which on this project would be `make docs-serve`. Having `make preview` on a project where documentation isn't the primary intent might not make sense.

**Pull request closed without merging**
