### PR TITLE
Apply the Syn default meta files

### PR DESCRIPTION
**Pull request by corvus-ch**

### CODE REVIEW

**Comment by tobru** [comment]
I'm not sure if a CHANGELOG makes sense here and if we should treat this repo 1:1 like the others. What do other think?

**Comment by corvus-ch** [comment]
> I'm not sure if a CHANGELOG makes sense here

I thought about this. If I am not mistaken, we do have a changelog for the VSHN handbook. In my opinion, it can be of value.

**Comment by srueg** [comment]
I guess the changelog only makes sense if we plan to have releases of the docs. Not sure this makes sense for documentation...

**Comment by corvus-ch** [comment]
I have removed the change log. We can add that again when we have a need for it. Please review and approve/request changes.

**Review by tobru — APPROVED** [review]

**Review by srueg — APPROVED** [review]

**Pull request merged**
