### PR TITLE
SYN-36: SDD 0015 - Vault

### PR DESCRIPTION
**Pull request by akosma**
Contents of SDD 0015

### CODE REVIEW

**Comment by tobru** [comment]
@srueg Can you please check if this PR contains the latest version of the SDD from the Wiki? If yes, please merge.

**Comment by srueg** [comment]
I updated the SDD yesterday. @akosma can you update to the latest version? I can also do it myself, if you want me to...

**Comment by srueg** [comment]
Since I'm actively working on this SDD right now, let's put it on hold and update the PR once it's done.

**Comment by srueg** [comment]
We finished the SDD in the wiki: https://wiki.vshn.net/pages/viewpage.action?pageId=153846674

**Comment by tobru** [comment]
Whatever happened, I didn't want to merge this PR. I'll create a new one.

**Pull request merged**
