### PR TITLE
Update Project Syn introduction sentence

### PR DESCRIPTION
**Pull request by tobru**
This PR updates the initial sentence which briefly introduces what Project Syn is all about.

## Checklist

- [X] Keep pull requests small so they can be easily reviewed.
- [X] Update the documentation.

### CODE REVIEW

**Comment by chrisglass** [comment]
Good stuff!

**Comment by tobru** [comment]
Does anyone have an idea how to fix the failing test? It complains about the generated Syntroduction HTML slides which doesn't make sense to be checked...

**Review by srueg — APPROVED** [review]

**Comment by corvus-ch** [comment]
Regarding tests. I am giving it a try in #99.

**Review by akosma — COMMENTED** [review]
Perfect!

**Pull request merged**
